function [foot, fric_coef] = Foot2(robot)
  
    knee_2_frame = robot.Joints(getJointIndices(robot, 'knee_front_rightR_link'));
    foot = ContactFrame(...
        'Name','Foot2',...
        'Reference',knee_2_frame,...
        'Offset',[0, 0, 0.24],...
        'R',[0,0,0],... % z-axis is the normal axis, so no rotation required
        'Type','PointContactWithFriction'...
        );
    
    fric_coef.mu = 0.3;
    fric_coef.gamma = 100;
end