function currentToTorque_func = currentToTorqueFunction(current)
% JN 1/30/2020 - jnorby@andrew.cmu.edu
%CURRENTTOTORQUEFUNCTION
%    CURRENTTOTORQUE_FUNC = CURRENTTOTORQUEFUNCTION(CURRENT)

%    This function was generated by the Symbolic Math Toolbox version 8.2.
%    04-Mar-2019 10:41:17

t2 = current.*9.282319622773603e-1;
t3 = current.^2;
t4 = t3.*8.616145757932789e-1;
t5 = t4+1.686778459918726e2;
t6 = sqrt(t5);
t7 = t2+t6;
currentToTorque_func = 1.0./t7.^(1.0./3.0).*(-5.525259527860618)+t7.^(1.0./3.0);
