function torqueToCurrent_func = torqueToCurrentFunction(torque)
%TORQUETOCURRENTFUNCTION
%    TORQUETOCURRENT_FUNC = TORQUETOCURRENTFUNCTION(TORQUE)

%    This function was generated by the Symbolic Math Toolbox version 8.2.
%    04-Mar-2019 10:41:17

t2 = torque.^2;
torqueToCurrent_func = torque.*8.928683377220816+t2.*torque.*5.386584607292347e-1;
