function [foot, fric_coef] = Foot0(robot)
  
    foot_0_frame = robot.Joints(getJointIndices(robot, 'jtoe0'));
    foot = ContactFrame(...
        'Name','Foot0',...
        'Reference',foot_0_frame,...
        'Offset',[0, 0, 0],...
        'R',[0,0,0],... % z-axis is the normal axis, so no rotation required
        'Type','PointContactWithFriction'...
        );
    
    fric_coef.mu = 1;
    fric_coef.gamma = 100;
end