function [foot, fric_coef] = Foot2(robot)
  
    foot_2_frame = robot.Joints(getJointIndices(robot, 'jtoe2'));
    foot = ContactFrame(...
        'Name','Foot0',...
        'Reference',foot_2_frame,...
        'Offset',[0, 0, 0],...
        'R',[0,0,0],... % z-axis is the normal axis, so no rotation required
        'Type','PointContactWithFriction'...
        );
    
    fric_coef.mu = 0.5;
    fric_coef.gamma = 100;
end