function [foot, fric_coef] = Foot3(robot)
  
    foot_3_frame = robot.Joints(getJointIndices(robot, 'jtoe3'));
    foot = ContactFrame(...
        'Name','Foot3',...
        'Reference',foot_3_frame,...
        'Offset',[0, 0, 0],...
        'R',[0,0,0],... % z-axis is the normal axis, so no rotation required
        'Type','PointContactWithFriction'...
        );
    
    fric_coef.mu = 1;
    fric_coef.gamma = 100;
end