function [foot, fric_coef] = Foot1(robot)
  
    foot_1_frame = robot.Joints(getJointIndices(robot, 'jtoe1'));
    foot = ContactFrame(...
        'Name','Foot1',...
        'Reference',foot_1_frame,...
        'Offset',[0, 0, 0],...
        'R',[0,0,0],... % z-axis is the normal axis, so no rotation required
        'Type','PointContactWithFriction'...
        );
    
    fric_coef.mu = 1;
    fric_coef.gamma = 100;
end